remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: TTS for twitch.tv/Gikerl_
description: All things you need to know on how to use the Text To Speech on Gikerl's Twitch Channel
show_downloads: "false"
